title: Gihyun Github
description: SLAM/CS

url: https://ggumnet.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: ggumnet
  instagram: parkgi_0205
  email: ggumnet@snu.ac.kr
  linkedin: 

google_analytics: "UA-58263416-1"

disqus:
    shortname: gihyun
